"use client";
import {useEffect,useMemo,useState} from "react";
import {UsersThree,CalendarDots,ChartLineUp,GearSix,SquaresFour,Plus,MapPin,Database} from "@phosphor-icons/react";
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,BarChart,Bar,Cell} from "recharts";
type View="team"|"calendar"|"analytics"; type Person={name:string;role:string,initials:string,color:string,project:string,address:string,database:string,status:string,note:string,stages:{name:string,value:number}[]};
const seed:Person[]=[
{name:"Алексей Морозов",role:"Lead 3D-моделлер",initials:"АМ",color:"#5277d8",project:"ЖК Северный парк",address:"Москва, ул. Полярная, 24",database:"BIM / Unreal Engine",status:"В графике",note:"Фасад готов. Сегодня — входные группы.",stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:84},{name:"Текстурирование",value:68},{name:"Финальная проверка",value:35}]},
{name:"Мария Волкова",role:"3D-моделлер",initials:"МВ",color:"#b96773",project:"БЦ Orbital",address:"Москва-Сити, участок 17",database:"Digital Twin Cloud",status:"В графике",note:"Сверяю инженерные этажи с BIM-моделью.",stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:92},{name:"Материалы и свет",value:76},{name:"Оптимизация",value:54}]},
{name:"Илья Соколов",role:"3D-моделлер",initials:"ИС",color:"#4f8f7a",project:"Кампус Технополис",address:"СПб, Пулковское ш., 40",database:"City Model DB",status:"Есть риск",note:"Ждём уточнения по кровле от проектировщиков.",stages:[{name:"Геометрия",value:100},{name:"Моделирование",value:61},{name:"UV-развёртка",value:42},{name:"Экспорт и QA",value:18}]},
{name:"Анна Лебедева",role:"Junior 3D-моделлер",initials:"АЛ",color:"#a37b4d",project:"Хаб Восток",address:"МО, Балашиха, промзона 7",database:"Asset Registry",status:"В графике",note:"Завершены складские корпуса A и B.",stages:[{name:"Референсы",value:100},{name:"Моделирование",value:73},{name:"Текстуры",value:58},{name:"Сборка сцены",value:41}]}
];
const history=[{d:"20",a:49,m:61,i:31,n:38},{d:"21",a:54,m:65,i:36,n:43},{d:"22",a:59,m:70,i:42,n:48},{d:"23",a:65,m:75,i:47,n:54},{d:"24",a:69,m:78,i:51,n:60},{d:"25",a:72,m:80,i:54,n:64},{d:"26",a:72,m:81,i:55,n:68}], colors=["#397ff4","#9a6edb","#42a37b","#ef9a45"];
export default function App(){const[view,setView]=useState<View>("team"),[people,setPeople]=useState(seed),[loaded,setLoaded]=useState(false);useEffect(()=>{const x=localStorage.getItem("twinteem-people");if(x)try{setPeople(JSON.parse(x))}catch{}setLoaded(true)},[]);useEffect(()=>{if(loaded)localStorage.setItem("twinteem-people",JSON.stringify(people))},[people,loaded]);const avg=(p:Person)=>Math.round(p.stages.reduce((a,s)=>a+s.value,0)/4),team=Math.round(people.reduce((a,p)=>a+avg(p),0)/4);const nav=(<>{([['team','Команда',UsersThree],['calendar','Календарь',CalendarDots],['analytics','Аналитика',ChartLineUp]] as const).map(([id,label,I])=><button className={view===id?"on":""} key={id} onClick={()=>setView(id)}><I size={19}/><span>{label}</span></button>)}</>);return <div className="app"><aside className="side"><div className="brand"><span className="logo"><SquaresFour size={20} weight="fill"/></span>TwinTeem</div><nav className="nav">{nav}<button><GearSix size={19}/>Настройки</button></nav></aside><main className="main"><header className="top"><div><div className="eyebrow">Воскресенье, 26 июля</div><h1>{view==='team'?'Команда':view==='calendar'?'Календарь':'Аналитика'}</h1></div><div className="buttons"><button className="btn">Сформировать отчёт</button><button className="btn dark"><Plus size={14}/> Новый проект</button></div></header>{view==='team'&&<><section className="kpis"><Kpi l="Прогресс команды" v={`${team}%`} s="+4.2% за неделю"/><Kpi l="Проектов в работе" v="4" s="Все активны"/><Kpi l="Средний KPI" v="91" s="+3 к прошлой неделе"/><Kpi l="Требуют внимания" v="1" s="Есть задержка"/></section><section className="people">{people.map((p,pi)=><article className="person" key={p.name}><div className="personHead"><div className="avatar" style={{background:p.color}}>{p.initials}</div><div className="grow"><h3>{p.name}</h3><div className="small">{p.role}</div></div><span className={`badge ${p.status==='Есть риск'?'risk':''}`}>{p.status}</span></div><div className="project"><strong>{p.project}</strong><div className="meta"><span><MapPin size={12}/> {p.address}</span><span><Database size={12}/> {p.database}</span></div></div><div className="row"><span>Общий прогресс</span><span>{avg(p)}%</span></div><Progress n={avg(p)}/><div className="stages">{p.stages.map((s,si)=><div key={s.name}><div className="stageTop"><span>{s.name}</span><span><input aria-label={s.name} type="range" value={s.value} onChange={e=>setPeople(old=>old.map((q,j)=>j===pi?{...q,stages:q.stages.map((t,k)=>k===si?{...t,value:+e.target.value}:t)}:q))}/> {s.value}%</span></div><Progress n={s.value}/></div>)}</div><textarea rows={2} value={p.note} onChange={e=>setPeople(old=>old.map((q,j)=>j===pi?{...q,note:e.target.value}:q))}/></article>)}</section></>}{view==='calendar'&&<Calendar/>}{view==='analytics'&&<Analytics people={people} avg={avg}/>}</main><nav className="mobile">{nav}</nav></div>}
function Kpi({l,v,s}:{l:string,v:string,s:string}){return <div className="card"><div className="small">{l}</div><div className="value">{v}</div><div className="small"><span className="green">↗</span> {s}</div></div>} function Progress({n}:{n:number}){return <div className="bar"><div className="fill" style={{width:`${n}%`}}/></div>}
function Calendar(){return <div className="panel"><div className="title">Июль 2026</div><div className="sub" style={{marginBottom:18}}>История ежедневного прогресса команды</div><div className="cal">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=><div className="weekday" key={x}>{x}</div>)}{Array.from({length:35},(_,i)=>i-2).map((d,i)=><div className={`day ${d<1||d>31?'dim':''} ${d===26?'today':''}`} key={i}>{d<1?30+d:d}{d>0&&d<=26&&<div className="activity" style={{opacity:.35+(d%5)/7}}/>}</div>)}</div></div>}
function Analytics({people,avg}:{people:Person[],avg:(p:Person)=>number}){const bars=useMemo(()=>people.map((p,i)=>({name:p.name.split(' ')[0],kpi:[94,96,78,87][i],progress:avg(p)})),[people]);return <div className="charts"><div className="panel"><div className="title">Темп прогресса</div><div className="sub">Изменение общего прогресса по дням</div><ResponsiveContainer width="100%" height={340}><LineChart data={history}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Line dataKey="a" stroke={colors[0]} strokeWidth={3} dot={false}/><Line dataKey="m" stroke={colors[1]} strokeWidth={3} dot={false}/><Line dataKey="i" stroke={colors[2]} strokeWidth={3} dot={false}/><Line dataKey="n" stroke={colors[3]} strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div><div className="panel"><div className="title">KPI сотрудников</div><div className="sub">Выполнение недельного плана, %</div><ResponsiveContainer width="100%" height={340}><BarChart data={bars} layout="vertical"><XAxis type="number" domain={[0,100]} hide/><YAxis dataKey="name" type="category" width={60} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="kpi" radius={[0,8,8,0]}>{bars.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="panel" style={{gridColumn:'1/-1'}}><div className="title">Сравнение сотрудников</div><div className="kpis" style={{marginTop:16,marginBottom:0}}>{bars.map((b,i)=><div className="project" key={b.name}><strong>{b.name}</strong><div className="value" style={{color:colors[i]}}>{b.progress}%</div><div className="small">KPI {b.kpi}</div></div>)}</div></div></div>}
