"use client";
import {useMemo,useState} from "react";
import {CaretLeft,CaretRight,CalendarPlus,X} from "@phosphor-icons/react";
import {memberProgress,migrateProjects,type Employee,type Project} from "@/lib/model";
import {dateKey,dailyRows,type Snapshot} from "@/lib/analytics";

type Props={snapshots:Snapshot[];people:Employee[];projects:Project[];projectFilter:string;admin:boolean;onSave:(snapshot:Snapshot)=>Promise<boolean>};
const cloneProjects=(projects:Project[])=>projects.map(p=>({...p,members:p.members.map(m=>({...m,stages:m.stages.map(s=>({...s}))}))}));

export default function CalendarPlanner({snapshots,people,projects,projectFilter,admin,onSave}:Props){
  const latest=snapshots.at(-1)?.date||dateKey(),[month,setMonth]=useState(()=>latest.slice(0,7)),[selected,setSelected]=useState(latest),[editing,setEditing]=useState<Snapshot|null>(null);
  const rows=useMemo(()=>dailyRows(snapshots,projectFilter),[snapshots,projectFilter]),byDate=useMemo(()=>new Map(snapshots.map(s=>[s.date,s])),[snapshots]),rowByDate=useMemo(()=>new Map(rows.map(r=>[r.date,r])),[rows]);
  const first=new Date(`${month}-01T12:00:00`),offset=(first.getDay()+6)%7,count=new Date(first.getFullYear(),first.getMonth()+1,0).getDate(),cells=Array.from({length:Math.ceil((offset+count)/7)*7},(_,i)=>i-offset+1),selectedSnapshot=byDate.get(selected),selectedRow=rowByDate.get(selected),future=selected>dateKey(),displayPeople=(selectedSnapshot?.people||people).filter(p=>selectedRow?.progress[p.id]!==undefined);
  const move=(n:number)=>{const next=new Date(first.getFullYear(),first.getMonth()+n,1);setMonth(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,"0")}`)};
  const openEditor=()=>{const basePeople=selectedSnapshot?.people||people,baseProjects=migrateProjects(basePeople,selectedSnapshot?.projects||projects);setEditing({date:selected,people:basePeople.map(p=>({...p,stages:p.stages.map(s=>({...s}))})),projects:cloneProjects(baseProjects)})};
  return <><div className="calendarLayout"><div className="panel"><div className="calendarHead"><div><div className="title">{first.toLocaleDateString("ru-RU",{month:"long",year:"numeric"})}</div><div className="sub">История и плановые данные команды</div></div><div className="monthNav"><button onClick={()=>move(-1)} aria-label="Предыдущий месяц"><CaretLeft/></button><button onClick={()=>{const now=dateKey();setMonth(now.slice(0,7));setSelected(now)}}>Сегодня</button><button onClick={()=>move(1)} aria-label="Следующий месяц"><CaretRight/></button></div></div><div className="cal">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=><div className="weekday" key={x}>{x}</div>)}{cells.map((day,i)=>{const key=`${month}-${String(day).padStart(2,"0")}`,row=rowByDate.get(key),active=byDate.has(key)&&Object.keys(row?.progress||{}).length>0,planned=key>dateKey();return <button className={`day ${day<1||day>count?"dim":""} ${key===dateKey()?"today":""} ${key===selected?"selected":""} ${planned&&active?"planned":""}`} disabled={day<1||day>count} onClick={()=>setSelected(key)} key={i}><span>{day>0&&day<=count?day:""}</span>{active&&<><div className="dayProgress"><i style={{width:`${row?.team||0}%`}}/></div><small>{planned?"План · ":""}{row?.team||0}%</small></>}</button>})}</div></div><div className="panel dayDetails"><div className="detailsHead"><div><div className="title">{new Date(`${selected}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}</div>{future&&<span className="planBadge">Плановая дата</span>}</div>{admin&&<button className="btn planBtn" onClick={openEditor}><CalendarPlus/> {selectedSnapshot?"Редактировать":"Добавить данные"}</button>}</div>{!selectedSnapshot||!displayPeople.length?<div className="emptyState">На эту дату данных по выбранному проекту пока нет.{admin&&<> Нажмите «Добавить данные», чтобы создать запись заранее.</>}</div>:<div className="snapshotList">{displayPeople.map(person=>{const gain=selectedRow?.delta[person.id]||0,kpi=selectedRow?.kpi[person.id]||0,current=selectedRow?.progress[person.id]||0;return <div className="snapshotRow" key={person.id}><span className="snapshotAvatar" style={{background:person.color}}>{person.initials}</span><div><b>{person.name}</b><small>{projectFilter==="all"?"Все назначения":projects.find(p=>p.id===projectFilter)?.name}</small></div><strong>{current}%</strong><span className={gain>=0?"gain":"loss"}>{gain>=0?"+":""}{gain}%</span><span className="kpiPill">{future?"План ":"KPI "}{kpi}%</span></div>})}<div className="calendarLegend">Будущие записи видны как план, но не включаются в фактическую аналитику и PDF до наступления даты.</div></div>}</div></div>{editing&&<PlanModal snapshot={editing} projectFilter={projectFilter} onClose={()=>setEditing(null)} onSave={async value=>{if(await onSave(value)){setSelected(value.date);setMonth(value.date.slice(0,7));setEditing(null)}}}/>}</>;
}

function PlanModal({snapshot,projectFilter,onClose,onSave}:{snapshot:Snapshot;projectFilter:string;onClose:()=>void;onSave:(snapshot:Snapshot)=>Promise<void>}){
  const[value,setValue]=useState(snapshot),[busy,setBusy]=useState(false),visible=(value.projects||[]).filter(p=>!p.archived&&(projectFilter==="all"||p.id===projectFilter));
  const stage=(projectId:string,employeeId:string,stageIndex:number,n:number)=>setValue(x=>({...x,projects:(x.projects||[]).map(p=>p.id===projectId?{...p,members:p.members.map(m=>m.employeeId===employeeId?{...m,stages:m.stages.map((s,si)=>si===stageIndex?{...s,value:Math.max(0,Math.min(100,n))}:s)}:m)}:p)}));
  return <div className="modalShade" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal planModal"><div className="modalTop"><div><h2>Данные календаря</h2><p>Фактическое состояние за прошлую дату или план на будущее.</p></div><button className="close" onClick={onClose}><X/></button></div><label className="planDate">Дата<input type="date" value={value.date} onChange={e=>setValue(x=>({...x,date:e.target.value}))}/></label><div className="planPeople">{visible.map(project=><section className="planProject" key={project.id}><h3>{project.name}</h3>{project.members.map(member=>{const person=value.people.find(p=>p.id===member.employeeId);return person?<div className="plannedMember" key={member.employeeId}><div className="planPersonHead"><span className="snapshotAvatar" style={{background:person.color}}>{person.initials}</span><div><b>{person.name}</b><small>{member.role} · загрузка {member.allocation}%</small></div><strong>{memberProgress(member)}%</strong></div><div className="planStages">{member.stages.map((s,si)=><label key={si}><span>{s.name}</span><input type="range" min="0" max="100" value={s.value} onChange={e=>stage(project.id,member.employeeId,si,+e.target.value)}/><input aria-label={`${project.name}: ${person.name}: ${s.name}`} type="number" min="0" max="100" value={s.value} onChange={e=>stage(project.id,member.employeeId,si,+e.target.value)}/><em>%</em></label>)}</div></div>:null})}</section>)}</div><div className="modalActions"><span/><button className="btn" onClick={onClose}>Отмена</button><button className="btn dark" disabled={busy||!value.date} onClick={async()=>{setBusy(true);await onSave(value);setBusy(false)}}>{busy?"Сохраняю…":"Сохранить дату"}</button></div></div></div>;
}
