export type Stage={name:string;value:number};
export type Employee={id:string;name:string;role:string;initials:string;color:string;avatar?:string;project:string;address:string;database:string;status:"В графике"|"Есть риск"|"Требует внимания";note:string;dailyTarget?:number;stages:Stage[]};
export type ObjectType="ОКС"|"МАФ"|"Террейн";
export type ProjectStatus="Планирование"|"В работе"|"Есть риск"|"На паузе"|"Завершён";
export type ProjectMember={employeeId:string;role:string;allocation:number;status:Employee["status"];note:string;stages:Stage[]};
export type Project={id:string;name:string;address:string;objectType:ObjectType;deadline:string;status:ProjectStatus;note:string;archived:boolean;members:ProjectMember[]};
export const average=(p:Employee)=>Math.round(p.stages.reduce((sum,s)=>sum+s.value,0)/Math.max(1,p.stages.length));
export const memberProgress=(member:ProjectMember)=>Math.round(member.stages.reduce((sum,s)=>sum+s.value,0)/Math.max(1,member.stages.length));
export const projectProgress=(project:Project)=>{const active=project.members.filter(m=>m.allocation>0),weight=active.reduce((sum,m)=>sum+m.allocation,0);return weight?Math.round(active.reduce((sum,m)=>sum+memberProgress(m)*m.allocation,0)/weight):0};
export const stageTemplate=(type:ObjectType):Stage[]=>({"ОКС":[{name:"Исходные данные",value:0},{name:"Моделирование",value:0},{name:"Текстуры",value:0},{name:"Проверка",value:0}],"МАФ":[{name:"Референсы",value:0},{name:"Моделирование",value:0},{name:"Материалы",value:0},{name:"Проверка",value:0}],"Террейн":[{name:"Исходные данные",value:0},{name:"Рельеф",value:0},{name:"Материалы",value:0},{name:"Оптимизация",value:0}]}[type].map(s=>({...s})));
export const migrateProjects=(people:Employee[],projects?:Project[]):Project[]=>Array.isArray(projects)&&projects.length?projects:people.map((p,index)=>({id:`project-${p.id}`,name:p.project||`Проект ${index+1}`,address:p.address||"",objectType:(p.database?.toLowerCase().includes("terrain")?"Террейн":"ОКС") as ObjectType,deadline:"",status:p.status==="Есть риск"?"Есть риск":"В работе",note:p.note||"",archived:false,members:[{employeeId:p.id,role:p.role||"Моделлер",allocation:100,status:p.status,note:p.note||"",stages:p.stages.map(s=>({...s}))}]}));
export const seed:Employee[]=[
{id:"alex",name:"Алексей Морозов",role:"Lead 3D-моделлер",initials:"АМ",color:"#5277d8",project:"ЖК Северный парк",address:"Москва, ул. Полярная, 24",database:"BIM / Unreal Engine",status:"В графике",note:"Фасад готов. Сегодня — входные группы.",dailyTarget:5,stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:84},{name:"Текстурирование",value:68},{name:"Финальная проверка",value:35}]},
{id:"maria",name:"Мария Волкова",role:"3D-моделлер",initials:"МВ",color:"#b96773",project:"БЦ Orbital",address:"Москва-Сити, участок 17",database:"Digital Twin Cloud",status:"В графике",note:"Сверяю инженерные этажи с BIM-моделью.",dailyTarget:5,stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:92},{name:"Материалы и свет",value:76},{name:"Оптимизация",value:54}]},
{id:"ilya",name:"Илья Соколов",role:"3D-моделлер",initials:"ИС",color:"#4f8f7a",project:"Кампус Технополис",address:"СПб, Пулковское ш., 40",database:"City Model DB",status:"Есть риск",note:"Ждём уточнения по кровле от проектировщиков.",dailyTarget:5,stages:[{name:"Геометрия",value:100},{name:"Моделирование",value:61},{name:"UV-развёртка",value:42},{name:"Экспорт и QA",value:18}]},
{id:"anna",name:"Анна Лебедева",role:"Junior 3D-моделлер",initials:"АЛ",color:"#a37b4d",project:"Хаб Восток",address:"МО, Балашиха, промзона 7",database:"Asset Registry",status:"В графике",note:"Завершены складские корпуса A и B.",dailyTarget:5,stages:[{name:"Референсы",value:100},{name:"Моделирование",value:73},{name:"Текстуры",value:58},{name:"Сборка сцены",value:41}]}
];
export const seedProjects=migrateProjects(seed);
