export type Stage={name:string;value:number};
export type Employee={id:string;name:string;role:string;initials:string;color:string;avatar?:string;project:string;address:string;database:string;status:"В графике"|"Есть риск"|"Требует внимания";note:string;stages:Stage[]};
export const average=(p:Employee)=>Math.round(p.stages.reduce((sum,s)=>sum+s.value,0)/Math.max(1,p.stages.length));
export const seed:Employee[]=[
{id:"alex",name:"Алексей Морозов",role:"Lead 3D-моделлер",initials:"АМ",color:"#5277d8",project:"ЖК Северный парк",address:"Москва, ул. Полярная, 24",database:"BIM / Unreal Engine",status:"В графике",note:"Фасад готов. Сегодня — входные группы.",stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:84},{name:"Текстурирование",value:68},{name:"Финальная проверка",value:35}]},
{id:"maria",name:"Мария Волкова",role:"3D-моделлер",initials:"МВ",color:"#b96773",project:"БЦ Orbital",address:"Москва-Сити, участок 17",database:"Digital Twin Cloud",status:"В графике",note:"Сверяю инженерные этажи с BIM-моделью.",stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:92},{name:"Материалы и свет",value:76},{name:"Оптимизация",value:54}]},
{id:"ilya",name:"Илья Соколов",role:"3D-моделлер",initials:"ИС",color:"#4f8f7a",project:"Кампус Технополис",address:"СПб, Пулковское ш., 40",database:"City Model DB",status:"Есть риск",note:"Ждём уточнения по кровле от проектировщиков.",stages:[{name:"Геометрия",value:100},{name:"Моделирование",value:61},{name:"UV-развёртка",value:42},{name:"Экспорт и QA",value:18}]},
{id:"anna",name:"Анна Лебедева",role:"Junior 3D-моделлер",initials:"АЛ",color:"#a37b4d",project:"Хаб Восток",address:"МО, Балашиха, промзона 7",database:"Asset Registry",status:"В графике",note:"Завершены складские корпуса A и B.",stages:[{name:"Референсы",value:100},{name:"Моделирование",value:73},{name:"Текстуры",value:58},{name:"Сборка сцены",value:41}]}
];
export const history=[{d:"20",a:49,m:61,i:31,n:38},{d:"21",a:54,m:65,i:36,n:43},{d:"22",a:59,m:70,i:42,n:48},{d:"23",a:65,m:75,i:47,n:54},{d:"24",a:69,m:78,i:51,n:60},{d:"25",a:72,m:80,i:54,n:64},{d:"26",a:72,m:81,i:55,n:68}];
