export type Stage={name:string;value:number};
export type Employee={id:string;name:string;role:string;initials:string;color:string;avatar?:string;project:string;address:string;database:string;status:"В графике"|"Есть риск"|"Требует внимания";note:string;dailyTarget?:number;stages:Stage[]};
export const average=(p:Employee)=>Math.round(p.stages.reduce((sum,s)=>sum+s.value,0)/Math.max(1,p.stages.length));
export const seed:Employee[]=[
{id:"alex",name:"Алексей Морозов",role:"Lead 3D-моделлер",initials:"АМ",color:"#5277d8",project:"ЖК Северный парк",address:"Москва, ул. Полярная, 24",database:"BIM / Unreal Engine",status:"В графике",note:"Фасад готов. Сегодня — входные группы.",dailyTarget:5,stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:84},{name:"Текстурирование",value:68},{name:"Финальная проверка",value:35}]},
{id:"maria",name:"Мария Волкова",role:"3D-моделлер",initials:"МВ",color:"#b96773",project:"БЦ Orbital",address:"Москва-Сити, участок 17",database:"Digital Twin Cloud",status:"В графике",note:"Сверяю инженерные этажи с BIM-моделью.",dailyTarget:5,stages:[{name:"Исходные данные",value:100},{name:"Моделирование",value:92},{name:"Материалы и свет",value:76},{name:"Оптимизация",value:54}]},
{id:"ilya",name:"Илья Соколов",role:"3D-моделлер",initials:"ИС",color:"#4f8f7a",project:"Кампус Технополис",address:"СПб, Пулковское ш., 40",database:"City Model DB",status:"Есть риск",note:"Ждём уточнения по кровле от проектировщиков.",dailyTarget:5,stages:[{name:"Геометрия",value:100},{name:"Моделирование",value:61},{name:"UV-развёртка",value:42},{name:"Экспорт и QA",value:18}]},
{id:"anna",name:"Анна Лебедева",role:"Junior 3D-моделлер",initials:"АЛ",color:"#a37b4d",project:"Хаб Восток",address:"МО, Балашиха, промзона 7",database:"Asset Registry",status:"В графике",note:"Завершены складские корпуса A и B.",dailyTarget:5,stages:[{name:"Референсы",value:100},{name:"Моделирование",value:73},{name:"Текстуры",value:58},{name:"Сборка сцены",value:41}]}
];
