import type {Employee} from "./model"; import {average,history} from "./model";
const esc=(s:string)=>s.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]!));
function bars(people:Employee[]){const w=560,h=150,max=100;return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">${people.map((p,i)=>{const y=12+i*34,n=average(p);return `<text x="0" y="${y+14}" font-size="11" fill="#333">${esc(p.name.split(" ")[0])}</text><rect x="78" y="${y}" width="410" height="18" rx="9" fill="#edf1f7"/><rect x="78" y="${y}" width="${410*n/max}" height="18" rx="9" fill="${p.color}"/><text x="500" y="${y+14}" font-size="11" fill="#333">${n}%</text>`}).join("")}</svg>`}
function lineChart(){const w=560,h=165,keys=["a","m","i","n"],colors=["#397ff4","#9a6edb","#42a37b","#ef9a45"];const lines=keys.map((k,ki)=>{const pts=history.map((x,i)=>`${35+i*82},${135-(x[k as keyof typeof x] as number)*1.15}`).join(" ");return `<polyline points="${pts}" fill="none" stroke="${colors[ki]}" stroke-width="3"/>`}).join("");return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg"><line x1="35" y1="135" x2="540" y2="135" stroke="#ccd3dd"/><line x1="35" y1="15" x2="35" y2="135" stroke="#ccd3dd"/>${lines}${history.map((x,i)=>`<text x="${29+i*82}" y="153" font-size="9" fill="#777">${x.d}.07</text>`).join("")}</svg>`}
export async function downloadReport(people:Employee[]){
  const mod=await import("pdfmake/build/pdfmake");const fonts=await import("pdfmake/build/vfs_fonts");const pdfMake:any=mod.default||mod;(pdfMake as any).vfs=(fonts as any).default?.pdfMake?.vfs||(fonts as any).default?.vfs||(fonts as any).pdfMake?.vfs||(fonts as any).default;
  const team=Math.round(people.reduce((s,p)=>s+average(p),0)/Math.max(1,people.length));
  const doc:any={pageSize:"A4",pageMargins:[38,42,38,42],defaultStyle:{font:"Roboto",fontSize:9,color:"#20232a"},footer:(p:number,c:number)=>({text:`TwinTeem • ${p} / ${c}`,alignment:"center",fontSize:8,color:"#8a8f99",margin:[0,14]}),content:[
    {text:"TwinTeem",fontSize:22,bold:true,color:"#176fe8"},{text:"ОТЧЁТ ПО КОМАНДЕ ЦИФРОВЫХ ДВОЙНИКОВ",fontSize:15,bold:true,margin:[0,8,0,2]},{text:new Date().toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"}),color:"#777",margin:[0,0,0,18]},
    {columns:[{text:`${team}%\nПрогресс команды`,style:"metric"},{text:`${people.length}\nПроектов в работе`,style:"metric"},{text:`${people.filter(p=>p.status!=="В графике").length}\nТребуют внимания`,style:"metric"}],columnGap:10,margin:[0,0,0,18]},
    {text:"Сравнение прогресса",style:"h2"},{svg:bars(people),width:520,margin:[0,5,0,15]},{text:"Темп прогресса за неделю",style:"h2"},{svg:lineChart(),width:520,margin:[0,5,0,18]},
    {text:"Детализация по сотрудникам",style:"h2",pageBreak:"before"},
    ...people.flatMap((p,i)=>[{columns:[p.avatar?{image:p.avatar,width:44,height:44,fit:[44,44],margin:[0,0,12,0]}:{canvas:[{type:"ellipse",x:22,y:22,r1:22,r2:22,color:p.color}],width:56},{width:"*",stack:[{text:p.name,fontSize:13,bold:true},{text:`${p.role} • ${p.status}`,color:p.status==="В графике"?"#24934d":"#c26d00"},{text:`${p.project} • ${p.address}`,margin:[0,4,0,0]}]},{text:`${average(p)}%`,fontSize:20,bold:true,color:p.color,alignment:"right"}],margin:[0,i?14:8,0,8]},
      {table:{widths:["*",55],body:p.stages.map(s=>[{text:s.name},{text:`${s.value}%`,bold:true,alignment:"right"}])},layout:{hLineColor:()=>"#e7e9ed",vLineWidth:()=>0,paddingTop:()=>5,paddingBottom:()=>5}},{text:`Комментарий: ${p.note||"—"}`,color:"#666",margin:[0,7,0,8]}])
  ],styles:{metric:{fontSize:12,bold:true,alignment:"center",color:"#20232a",fillColor:"#f2f5f9",margin:[8,10]},h2:{fontSize:12,bold:true,color:"#20232a",margin:[0,6,0,4]}}};
  const blob:Blob=await new Promise((resolve,reject)=>{try{pdfMake.createPdf(doc).getBlob(resolve)}catch(e){reject(e)}});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`TwinTeem-report-${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
