import type {Employee} from "./model";
import {average} from "./model";
import {dailyRows,employeeMetrics,type Snapshot} from "./analytics";
const esc=(s:string)=>s.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]!));
function bars(people:Employee[]){const w=560,h=Math.max(150,people.length*34+20);return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">${people.map((p,i)=>{const y=12+i*34,n=average(p);return `<text x="0" y="${y+14}" font-size="11" fill="#333">${esc(p.name.split(" ")[0])}</text><rect x="78" y="${y}" width="410" height="18" rx="9" fill="#edf1f7"/><rect x="78" y="${y}" width="${410*n/100}" height="18" rx="9" fill="${p.color}"/><text x="500" y="${y+14}" font-size="11" fill="#333">${n}%</text>`}).join("")}</svg>`}
function lineChart(people:Employee[],snapshots:Snapshot[]){const rows=dailyRows(snapshots.slice(-14)),w=560,h=170,palette=["#397ff4","#9a6edb","#42a37b","#ef9a45","#e65f8e","#65758b"];if(rows.length<2)return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg"><rect width="${w}" height="${h}" rx="12" fill="#f6f7f9"/><text x="280" y="86" text-anchor="middle" font-size="11" fill="#777">История появится после второго дня работы</text></svg>`;const usable=people.slice(0,6),step=480/Math.max(1,rows.length-1),lines=usable.map((p,pi)=>{const pts=rows.map((row,i)=>`${45+i*step},${140-(row.progress[p.id]||0)*1.15}`).join(" ");return `<polyline points="${pts}" fill="none" stroke="${palette[pi]}" stroke-width="3"/>`}).join("");return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg"><line x1="45" y1="140" x2="530" y2="140" stroke="#ccd3dd"/><line x1="45" y1="20" x2="45" y2="140" stroke="#ccd3dd"/>${lines}${rows.map((row,i)=>`<text x="${38+i*step}" y="158" font-size="8" fill="#777">${row.label}</text>`).join("")}</svg>`}
export async function downloadReport(people:Employee[],snapshots:Snapshot[]=[]){
  const mod=await import("pdfmake/build/pdfmake"),fonts=await import("pdfmake/build/vfs_fonts"),pdfMake:any=mod.default||mod;(pdfMake as any).vfs=(fonts as any).default?.pdfMake?.vfs||(fonts as any).default?.vfs||(fonts as any).pdfMake?.vfs||(fonts as any).default;
  const team=Math.round(people.reduce((s,p)=>s+average(p),0)/Math.max(1,people.length)),metrics=employeeMetrics(snapshots.slice(-30),people),teamKpi=Math.round(metrics.reduce((s,p)=>s+p.kpi,0)/Math.max(1,metrics.length));
  const doc:any={pageSize:"A4",pageMargins:[38,42,38,42],defaultStyle:{font:"Roboto",fontSize:9,color:"#20232a"},footer:(p:number,c:number)=>({text:`TwinTeem • ${p} / ${c}`,alignment:"center",fontSize:8,color:"#8a8f99",margin:[0,14]}),content:[
    {text:"TwinTeem",fontSize:22,bold:true,color:"#176fe8"},{text:"ОТЧЁТ ПО КОМАНДЕ ЦИФРОВЫХ ДВОЙНИКОВ",fontSize:15,bold:true,margin:[0,8,0,2]},{text:new Date().toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"}),color:"#777",margin:[0,0,0,18]},
    {columns:[{text:`${team}%\nПрогресс команды`,style:"metric"},{text:`${teamKpi}%\nСредний KPI`,style:"metric"},{text:`${people.filter(p=>p.status!=="В графике").length}\nТребуют внимания`,style:"metric"}],columnGap:10,margin:[0,0,0,18]},
    {text:"Сравнение прогресса",style:"h2"},{svg:bars(people),width:520,margin:[0,5,0,15]},{text:"Темп прогресса",style:"h2"},{svg:lineChart(people,snapshots),width:520,margin:[0,5,0,18]},
    {text:"Детализация по сотрудникам",style:"h2",pageBreak:"before"},
    ...people.flatMap((p,i)=>{const metric=metrics.find(m=>m.id===p.id);return [{columns:[p.avatar?{image:p.avatar,width:44,height:44,fit:[44,44],margin:[0,0,12,0]}:{canvas:[{type:"ellipse",x:22,y:22,r1:22,r2:22,color:p.color}],width:56},{width:"*",stack:[{text:p.name,fontSize:13,bold:true},{text:`${p.role} • ${p.status}`,color:p.status==="В графике"?"#24934d":"#c26d00"},{text:`${p.project} • ${p.address}`,margin:[0,4,0,0]}]},{stack:[{text:`${average(p)}%`,fontSize:20,bold:true,color:p.color,alignment:"right"},{text:`KPI ${metric?.kpi||0}%`,fontSize:9,alignment:"right",color:"#666"}]}],margin:[0,i?14:8,0,8]},
      {table:{widths:["*",55],body:p.stages.map(s=>[{text:s.name},{text:`${s.value}%`,bold:true,alignment:"right"}])},layout:{hLineColor:()=>"#e7e9ed",vLineWidth:()=>0,paddingTop:()=>5,paddingBottom:()=>5}},{text:`Дневная норма: ${p.dailyTarget||5}% • Вклад за 30 дней: ${metric?.contribution||0} п.п.`,color:"#56657a",margin:[0,7,0,2]},{text:`Комментарий: ${p.note||"—"}`,color:"#666",margin:[0,4,0,8]}]})
  ],styles:{metric:{fontSize:12,bold:true,alignment:"center",color:"#20232a",fillColor:"#f2f5f9",margin:[8,10]},h2:{fontSize:12,bold:true,color:"#20232a",margin:[0,6,0,4]}}};
  const blob:Blob=await new Promise((resolve,reject)=>{try{pdfMake.createPdf(doc).getBlob(resolve)}catch(e){reject(e)}}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`TwinTeem-report-${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
