import type {Employee,Project} from "./model";
import {memberProgress,projectProgress} from "./model";
import {dailyRows,employeeMetrics,type Snapshot} from "./analytics";
const esc=(s:string)=>s.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]!));
function bars(projects:Project[]){const w=560,h=Math.max(110,projects.length*34+20),colors=["#397ff4","#9a6edb","#42a37b","#ef9a45"];return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">${projects.map((p,i)=>{const y=12+i*34,n=projectProgress(p);return `<text x="0" y="${y+14}" font-size="10" fill="#333">${esc(p.name.slice(0,18))}</text><rect x="125" y="${y}" width="360" height="18" rx="9" fill="#edf1f7"/><rect x="125" y="${y}" width="${360*n/100}" height="18" rx="9" fill="${colors[i%colors.length]}"/><text x="497" y="${y+14}" font-size="11" fill="#333">${n}%</text>`}).join("")}</svg>`}
function lineChart(people:Employee[],snapshots:Snapshot[],projectId:string){const rows=dailyRows(snapshots.slice(-14),projectId),metrics=employeeMetrics(snapshots,people,undefined,projectId),w=560,h=170,palette=["#397ff4","#9a6edb","#42a37b","#ef9a45","#e65f8e"];if(rows.length<2)return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg"><rect width="${w}" height="${h}" rx="12" fill="#f6f7f9"/><text x="280" y="86" text-anchor="middle" font-size="11" fill="#777">История появится после второго дня работы</text></svg>`;const step=480/Math.max(1,rows.length-1),lines=metrics.slice(0,6).map((m,pi)=>`<polyline points="${rows.map((row,i)=>`${45+i*step},${140-(row.progress[m.id]||0)*1.15}`).join(" ")}" fill="none" stroke="${palette[pi%palette.length]}" stroke-width="3"/>`).join("");return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg"><line x1="45" y1="140" x2="530" y2="140" stroke="#ccd3dd"/><line x1="45" y1="20" x2="45" y2="140" stroke="#ccd3dd"/>${lines}${rows.map((row,i)=>`<text x="${38+i*step}" y="158" font-size="8" fill="#777">${row.label}</text>`).join("")}</svg>`}
export async function downloadReport(people:Employee[],projects:Project[],snapshots:Snapshot[]=[],projectId="all"){
  const mod=await import("pdfmake/build/pdfmake"),fonts=await import("pdfmake/build/vfs_fonts"),pdfMake:any=mod.default||mod;(pdfMake as any).vfs=(fonts as any).default?.pdfMake?.vfs||(fonts as any).default?.vfs||(fonts as any).pdfMake?.vfs||(fonts as any).default;
  const selected=projects.filter(p=>!p.archived&&(projectId==="all"||p.id===projectId)),metrics=employeeMetrics(snapshots.slice(-30),people,projects,projectId),team=Math.round(selected.reduce((s,p)=>s+projectProgress(p),0)/Math.max(1,selected.length)),teamKpi=Math.round(metrics.reduce((s,p)=>s+p.kpi,0)/Math.max(1,metrics.length)),title=projectId==="all"?"Все активные проекты":selected[0]?.name||"Проект";
  const doc:any={pageSize:"A4",pageMargins:[38,42,38,42],defaultStyle:{font:"Roboto",fontSize:9,color:"#20232a"},footer:(p:number,c:number)=>({text:`TwinTeem • ${p} / ${c}`,alignment:"center",fontSize:8,color:"#8a8f99",margin:[0,14]}),content:[{text:"TwinTeem",fontSize:22,bold:true,color:"#176fe8"},{text:"ОТЧЁТ ПО ПРОЕКТАМ",fontSize:15,bold:true,margin:[0,8,0,2]},{text:`${title} • ${new Date().toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}`,color:"#777",margin:[0,0,0,18]},{columns:[{text:`${team}%\nОбщий прогресс`,style:"metric"},{text:`${selected.length}\nПроектов`,style:"metric"},{text:`${teamKpi}%\nСредний KPI`,style:"metric"}],columnGap:10,margin:[0,0,0,18]},{text:"Прогресс проектов",style:"h2"},{svg:bars(selected),width:520,margin:[0,5,0,15]},{text:"Темп прогресса",style:"h2"},{svg:lineChart(people,snapshots,projectId),width:520,margin:[0,5,0,18]},{text:"Детализация",style:"h2",pageBreak:"before"},...selected.flatMap((project,pi)=>[{text:project.name,fontSize:15,bold:true,color:"#176fe8",margin:[0,pi?18:8,0,3]},{text:`${project.objectType} • ${project.address||"Адрес не указан"} • дедлайн ${project.deadline?new Date(`${project.deadline}T12:00:00`).toLocaleDateString("ru-RU"):"не задан"} • ${project.status}`,color:"#666",margin:[0,0,0,8]},{columns:[{text:`${projectProgress(project)}%\nПрогресс`,style:"miniMetric"},{text:`${project.members.length}\nУчастников`,style:"miniMetric"},{text:`${project.members.reduce((s,m)=>s+m.allocation,0)}%\nСуммарная загрузка`,style:"miniMetric"}],columnGap:8,margin:[0,0,0,10]},...project.members.flatMap(member=>{const person=people.find(p=>p.id===member.employeeId),metric=metrics.find(m=>m.id===member.employeeId);if(!person)return[];return[{columns:[{text:person.name,bold:true},{text:`${member.role} • загрузка ${member.allocation}%`,color:"#666"},{text:`${memberProgress(member)}%`,bold:true,alignment:"right"}],margin:[0,7,0,4]},{table:{widths:["*",55],body:member.stages.map(s=>[{text:s.name},{text:`${s.value}%`,bold:true,alignment:"right"}])},layout:{hLineColor:()=>"#e7e9ed",vLineWidth:()=>0,paddingTop:()=>4,paddingBottom:()=>4}},{text:`KPI ${metric?.kpi||0}% • ${member.status} • ${member.note||"Без комментария"}`,color:"#666",margin:[0,5,0,5]}]})])],styles:{metric:{fontSize:12,bold:true,alignment:"center",fillColor:"#f2f5f9",margin:[8,10]},miniMetric:{fontSize:10,bold:true,alignment:"center",fillColor:"#f6f7f9",margin:[6,7]},h2:{fontSize:12,bold:true,margin:[0,6,0,4]}}};
  const blob:Blob=await new Promise((resolve,reject)=>{try{pdfMake.createPdf(doc).getBlob(resolve)}catch(e){reject(e)}}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`TwinTeem-${projectId==="all"?"all-projects":projectId}-${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
